sfdx/force-app/main/default/objects/Stripe_Account__c/Stripe_Account__c.object-meta.xml
<CustomObject>
    <description>Custom object representing a connected Stripe Account.</description>
    <label>Stripe Account</label>
    <nameField>
        <label>Stripe Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Stripe_Account__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>Composite key is a generated, unique key the connector used identify this Stripe Account connection. This is generated by concatenating of the Stripe Account ID and the Stripe Account livemode</description>
    <externalId>true</externalId>
    <inlineHelpText>Composite key is a generated, unique key the connector used identify this Stripe Account connection. This is generated by concatenating of the Stripe Account ID and the Stripe Account livemode</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Account__c/fields/Is_Live_Mode__c.field-meta.xml
<CustomField>
    <fullName>Is_Live_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this connection in Live mode?</description>
    <inlineHelpText>Is this connection in Live mode?</inlineHelpText>
    <label>Is Live Mode?</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Account__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this connection the Primary connection?</description>
    <inlineHelpText>Is this connection the Primary connection?</inlineHelpText>
    <label>Is Primary?</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Account__c/fields/Stripe_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_ID__c</fullName>
    <label>Stripe Account Id</label>
    <description>The ID of the Stripe Account this record represents.</description>
    <inlineHelpText>The ID of the Stripe Account this record represents.</inlineHelpText>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/classes/PostInstallClass.cls
/**
 * Created by rpena on 3/11/2024.
 */

global class PostInstallClass implements InstallHandler {
    global void onInstall(InstallContext context) {
        if((constants.NAMESPACE == 'QaStripeConnect' && context.previousVersion()?.compareTo(new Version(1,96)) < 0)
                || (constants.NAMESPACE == 'stripeConnector' && context.previousVersion()?.compareTo(new Version(2,8)) < 0) || constants.NAMESPACE == 'c') {
            //get response structure
            String route = UriTargetsV1.getConfigEndpoint();
            HttpResponse response = utilities.makeCallout(route, 'GET');

            //get stripe_account_id from response JSON
            Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
            Map<String, Object> connectionStatus = (Map<String, Object>)result.get('connection_status');
            String stripe_id = connectionStatus.get('stripe_account_id').toString();
            Boolean liveMode = Sentry_Environment.getInstanceType() == Sentry_Environment.InstanceType.valueOf('PRODUCTION');

            //create Stripe_Account__c record if there are no other Stripe Accounts
            List<Stripe_Account__c> existingStripeAccounts = [SELECT Id, External_ID__c FROM Stripe_Account__c WHERE External_ID__c != NULL];
            if(existingStripeAccounts.size() == 0){
                Stripe_Account__c stripeAccount = new Stripe_Account__c();
                stripeAccount.Stripe_ID__c = stripe_id;
                stripeAccount.Is_Live_Mode__c = liveMode;
                stripeAccount.External_ID__c = stripe_id + '|' + liveMode;
                stripeAccount.Name = stripe_id;
                stripeAccount.Is_Primary__c = true;
                insert(stripeAccount);
            }
        }
    }
}