sfdx/force-app/main/default/objects/Quote_Line_Stripe_Coupon_Association__c/Quote_Line_Stripe_Coupon_Association__c.object-meta.xml
<CustomObject>
    <description>Custom junction object linking a Stripe Coupon and a CPQ Quote Line.</description>
    <label>Quote Line Stripe Coupon Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Quote Line Stripe Coupon Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Stripe Coupon Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Quote_Line_Stripe_Coupon_Association__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipName>Quote_Line_In_Association</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx/force-app/main/default/objects/Quote_Line_Stripe_Coupon_Association__c/fields/Quote_Stripe_Coupon__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stripe_Coupon__c</fullName>
    <label>Quote Stripe Coupon</label>
    <referenceTo>Quote_Stripe_Coupon__c</referenceTo>
    <relationshipName>Stripe_Coupon_In_Quote_Line_Association</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx/force-app/main/default/objects/Quote_Stripe_Coupon__c/Quote_Stripe_Coupon__c.object-meta.xml
<CustomObject>
    <description>Custom object representing a Stripe Coupon.</description>
    <label>Quote Stripe Coupon</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Coupon Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Stripe Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <validationRules>
        <fullName>Duration_In_Months_Set_For_Repeating</fullName>
        <description>When you use the value repeating for duration, you must specify duration_in_months as the number of months that the coupon repeatedly applies to.</description>
        <active>true</active>
        <errorConditionFormula>AND(ISPICKVAL(Duration__c, "repeating"), ISBLANK(Duration_In_Months__c))</errorConditionFormula>
        <errorMessage>The Duration_In_Months__c param must be set when creating a coupon with a repeating duration.</errorMessage>
    </validationRules>
   <validationRules>
        <fullName>Either_Coupon_Type_Off_Is_Set</fullName>
        <description>Stripe Coupon has either Percent Off or Amount Off set.</description>
        <active>true</active>
        <errorConditionFormula>AND(ISBLANK(Amount_Off__c), ISBLANK(Percent_Off__c))</errorConditionFormula>
        <errorMessage>Must provide Percent_Off__c or Amount_Off__c on a Stripe Coupon.</errorMessage>
    </validationRules>
    <validationRules>
        <fullName>Only_One_Coupon_Type_Off_Is_Set</fullName>
        <description>Stripe Coupon does not have both Percent Off or Amount Off set.</description>
        <active>true</active>
        <errorConditionFormula>AND(NOT(ISBLANK(Amount_Off__c)), NOT(ISBLANK(Percent_Off__c)))</errorConditionFormula>
        <errorMessage>Received both Percent_Off__c and Amount_Off__c parameters. Please pass in only one.</errorMessage>
    </validationRules>
    <validationRules>
        <fullName>Percent_Off_Is_In_Range</fullName>
        <description>Percent_Off__c value should be between 0 and 100.</description>
        <active>true</active>
        <errorConditionFormula>AND(NOT(ISBLANK(Percent_Off__c)), Percent_Off__c > 100.0)</errorConditionFormula>
        <errorMessage>Percent_Off__c value must be greater than 0 and less or equal to 100.</errorMessage>
    </validationRules>
    <validationRules>
        <fullName>Amount_Off_and_Percent_Off_Not_Updated</fullName>
        <description>You cannot change `Amount_Off__c` or `Percent_Off__c` after the coupon is created in Stripe.</description>
        <active>true</active>
        <errorConditionFormula>AND(NOT(ISBLANK(Stripe_ID__c)), OR(ISCHANGED(Amount_Off__c), ISCHANGED(Percent_Off__c)))</errorConditionFormula>
        <errorMessage>You cannot update Amount_Off__c or Percent_Off__c after the coupon has been created.</errorMessage>
    </validationRules>
    <validationRules>
        <fullName>Duration_Not_Updated</fullName>
        <description>You cannot change `Duration__c` after the coupon is created in Stripe.</description>
        <active>true</active>
        <errorConditionFormula>AND(NOT(ISBLANK(Stripe_ID__c)), OR(ISCHANGED(Duration__c)))</errorConditionFormula>
        <errorMessage>You cannot update Duration__c after the coupon has been created.</errorMessage>
    </validationRules>
</CustomObject>

sfdx/force-app/main/default/objects/Quote_Stripe_Coupon_Association__c/Quote_Stripe_Coupon_Association__c.object-meta.xml
<CustomObject>
    <description>Custom junction object linking a Stripe Coupon and a CPQ Quote.</description>
    <label>Quote Stripe Coupon Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Quote Stripe Coupon Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Stripe Coupon Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Quote_Stripe_Coupon_Association__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <description>The Id of the Quote Record in the Salesforce data set.</description>
    <inlineHelpText>The Id of the Quote Record in Salesforce.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipName>Quote_In_Association</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx/force-app/main/default/objects/Quote_Stripe_Coupon_Association__c/fields/Quote_Stripe_Coupon__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stripe_Coupon__c</fullName>
    <label>Quote Stripe Coupon</label>
    <referenceTo>Quote_Stripe_Coupon__c</referenceTo>
    <relationshipName>Stripe_Coupon_In_Quote_Association</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx/force-app/main/default/classes/QuoteCouponAssociationTriggerHandler.cls
/**
 * Created by jmather-c on 2/17/23.
 */

public with sharing class QuoteCouponAssociationTriggerHandler {
    // allows us to bypass the trigger in tests
    @TestVisible
    private static Boolean TRIGGER_ENABLED = true;

    // left non-static and non-final so we can tweak and test in non-multi-curr envs
    @TestVisible
    private String ASSOC_FIELD_CURRENCY_ISO_CODE = constants.FIELD_CURRENCY_ISO_CODE;
    @TestVisible
    private String QUOTE_FIELD_CURRENCY_ISO_CODE = constants.FIELD_CURRENCY_ISO_CODE;
    @TestVisible
    private String COUPON_FIELD_CURRENCY_ISO_CODE = constants.FIELD_CURRENCY_ISO_CODE;
    @TestVisible
    private static final String LABEL_QUOTE = SBQQ__Quote__c.SObjectType.getDescribe().getLabel();
    @TestVisible
    private static final String LABEL_QUOTE_COUPON = Quote_Stripe_Coupon__c.SObjectType.getDescribe().getLabel();
    @TestVisible
    private static final String LABEL_QUOTE_STRIPE_COUPON_ASSOC = Quote_Stripe_Coupon_Association__c.SObjectType.getDescribe().getLabel();
    @TestVisible
    private static final String LABEL_QUOTE_LINE_STRIPE_COUPON_ASSOC = Quote_Line_Stripe_Coupon_Association__c.SObjectType.getDescribe().getLabel();
    @TestVisible
    private static final String FORMAT_DEPENDENT_ERROR_MESSAGE = 'The Currency of the {0} ({1}) does not match the Currency of the {2} ({3}).';
    private static final String FORMAT_ASSOC_ERROR_MESSAGE = 'The Currency of the {0} ({1}) does not match the Currency of the {2} ({3}) or the {4} ({5}).';

    public void process(List<Quote_Stripe_Coupon_Association__c> quoteAssocs) {
        if (TRIGGER_ENABLED == false) {
            return;
        }

        Set<Id> couponIds = pickIds(quoteAssocs, Quote_Stripe_Coupon_Association__c.Quote_Stripe_Coupon__c);
        Set<Id> quoteIds = pickIds(quoteAssocs, Quote_Stripe_Coupon_Association__c.Quote__c);

        Map<Id, String> couponCurrencies = getCouponIsoCodeMap(couponIds);
        Map<Id, String> quoteCurrencies = getQuoteIsoCodeMap(quoteIds);

        for (Quote_Stripe_Coupon_Association__c assoc : quoteAssocs) {
            String couponCurrency = couponCurrencies.get(assoc.Quote_Stripe_Coupon__c);
            String quoteCurrency = quoteCurrencies.get(assoc.Quote__c);
            String assocCurrency = (String) assoc.get(ASSOC_FIELD_CURRENCY_ISO_CODE);

            // this would only be null if the coupon did not end up being queried because it is not an Amount Off coupon
            if (couponCurrency == null) {
                continue;
            }

            validateCurrency(assocCurrency, quoteCurrency, couponCurrency, assoc, LABEL_QUOTE_STRIPE_COUPON_ASSOC);
        }
    }

    public void process(List<Quote_Line_Stripe_Coupon_Association__c> quoteLineAssocs) {
        if (TRIGGER_ENABLED == false) {
            return;
        }

        Set<Id> couponIds = pickIds(quoteLineAssocs, Quote_Line_Stripe_Coupon_Association__c.Quote_Stripe_Coupon__c);
        Set<Id> quoteLineIds = pickIds(quoteLineAssocs, Quote_Line_Stripe_Coupon_Association__c.Quote_Line__c);

        Map<Id, String> couponCurrencies = getCouponIsoCodeMap(couponIds);
        Map<Id, String> quoteLineCurrencies = getQuoteLineIsoCodeMap(quoteLineIds);

        for (Quote_Line_Stripe_Coupon_Association__c assoc : quoteLineAssocs) {
            String couponCurrency = couponCurrencies.get(assoc.Quote_Stripe_Coupon__c);
            String quoteCurrency = quoteLineCurrencies.get(assoc.Quote_Line__c);
            String assocCurrency = (String) assoc.get(ASSOC_FIELD_CURRENCY_ISO_CODE);

            // this would only be null if the coupon did not end up being queried because it is not an Amount Off coupon
            if (couponCurrency == null) {
                continue;
            }

            validateCurrency(assocCurrency, quoteCurrency, couponCurrency, assoc, LABEL_QUOTE_LINE_STRIPE_COUPON_ASSOC);
        }
    }

    @TestVisible
    private void validateCurrency(String assocCurrency, String quoteCurrency, String couponCurrency, SObject obj, String objLabel) {
        Boolean check1 = assocCurrency == couponCurrency;
        Boolean check2 = assocCurrency == quoteCurrency;
        Boolean check3 = couponCurrency == quoteCurrency;

        System.debug('Checks: ' + check1 + ', ' + check2 + ', ' + check3);

        if (check1 && check2 && check3) {
            return;
        }

        if (check1 == false && check2 == false) {
            String errorMsg = String.format(FORMAT_ASSOC_ERROR_MESSAGE,
                    new String[] { objLabel, assocCurrency, LABEL_QUOTE, quoteCurrency, LABEL_QUOTE_COUPON, couponCurrency});
            obj.addError(ASSOC_FIELD_CURRENCY_ISO_CODE, errorMsg);
        }

        if (check3 == false) {
            String errorMsg = String.format(FORMAT_DEPENDENT_ERROR_MESSAGE,
                    new String[] { LABEL_QUOTE, quoteCurrency, LABEL_QUOTE_COUPON, couponCurrency });
            obj.addError(errorMsg);
        }
    }

    @TestVisible
    private Map<Id, String> getCouponIsoCodeMap(Set<Id> couponIds) {
        String ids = utilities.idsToQueryString(couponIds);

        String query = 'SELECT Id, ' + COUPON_FIELD_CURRENCY_ISO_CODE + ' FROM Quote_Stripe_Coupon__c WHERE Id IN ' + ids;
        // make the validation not apply to % off coupons.
        query += ' AND Amount_Off__c > 0';
        List<SObject> coupons = Database.query(query);

        Map<Id, String> result = new Map<Id, String>();

        for (SObject coupon : coupons) {
            result.put(coupon.Id, (String) coupon.get(COUPON_FIELD_CURRENCY_ISO_CODE));
        }

        return result;
    }

    @TestVisible
    private Map<Id, String> getQuoteIsoCodeMap(Set<Id> quoteIds) {
        String ids = utilities.idsToQueryString(quoteIds);
        String query = 'SELECT Id, ' + QUOTE_FIELD_CURRENCY_ISO_CODE + ' FROM SBQQ__Quote__c WHERE Id IN ' + ids;
        List<SObject> quotes = Database.query(query);

        Map<Id, String> result = new Map<Id, String>();

        for (SObject quote : quotes) {
            result.put(quote.Id, (String) quote.get(QUOTE_FIELD_CURRENCY_ISO_CODE));
        }

        return result;
    }

    @TestVisible
    private Map<Id, String> getQuoteLineIsoCodeMap(Set<Id> quoteLineIds) {
        String ids = utilities.idsToQueryString(quoteLineIds);
        String query = 'SELECT Id, SBQQ__Quote__r.' + QUOTE_FIELD_CURRENCY_ISO_CODE + ' FROM SBQQ__QuoteLine__c WHERE Id IN ' + ids;
        List<SObject> quoteLines = Database.query(query);

        Map<Id, String> result = new Map<Id, String>();

        for (SObject quoteLine : quoteLines) {
            SObject quote = quoteLine.getSObject('SBQQ__Quote__r');
            result.put(quoteLine.Id, (String) quote.get(QUOTE_FIELD_CURRENCY_ISO_CODE));
        }

        return result;
    }

    @TestVisible
    private Set<Id> pickIds(List<SObject> objs, SObjectField field) {
        return pickIds(objs, field.getDescribe().getName());
    }

    private Set<Id> pickIds(List<SObject> objs, String field) {
        Set<Id> result = new Set<Id>();

        for (SObject obj : objs) {
            result.add((String) obj.get(field));
        }

        return result;
    }
}