sfdx/force-app/main/default/objects/Sentry_Active_Config__c/Sentry_Active_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The active Configuration to use for Sentry</description>
    <label>Sentry Active Config</label>
</CustomObject>

sfdx/force-app/main/default/objects/Sentry_Active_Config__c/fields/Environment_Name__c.field-meta.xml
<CustomField>
    <fullName>Environment_Name__c</fullName>
    <description>The name of the environment to use in place of the calculated environment from the URL.</description>
    <inlineHelpText>The name of the environment to use in place of the calculated environment from the URL.</inlineHelpText>
    <label>Environment Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Sentry_Active_Config__c/fields/IsDebug__c.field-meta.xml
<CustomField>
    <fullName>IsDebug__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Debug Enabled?</description>
    <inlineHelpText>Turns on verbose logging to Sentry.</inlineHelpText>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Sentry_Active_Config__c/fields/IsIssueCreationDisabled__c.field-meta.xml
<CustomField>
    <fullName>IsIssueCreationDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Issue Creation Disabled?</description>
    <inlineHelpText>Disables creating new issues in Sentry.</inlineHelpText>
    <label>Issue Creation Disabled?</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Sentry_Active_Config__c/fields/Sentry_Config__c.field-meta.xml
<CustomField>
    <fullName>Sentry_Config__c</fullName>
    <defaultValue>&quot;Default&quot;</defaultValue>
    <description>The DeveloperName of the Sentry_Config__mdt entry to use for configuration.</description>
    <inlineHelpText>The DeveloperName of the Sentry_Config__mdt entry to use for configuration.</inlineHelpText>
    <label>Sentry Config DeveloperName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/classes/SentryTest.cls
/**
 * @description       : 
 * @author            : jmather
 * @group             : 
 * @last modified on  : 02-11-2022
 * @last modified by  : Stripe
 * Modifications Log 
 * Ver   Date         Author    Modification
 * 1.0   08-10-2019   jmather   Initial Version
 * 1.1   02-11-2022   Stripe    Moved mock callout into this class
**/


@IsTest
public with sharing class SentryTest {
    private class MyException extends Sentry_Exception {}
    private class SYS_CustomException extends Exception {}
    @IsTest
    static void Record() {
        Exception ex;

        Test.setMock(HttpCalloutMock.class, new Sentry_ApiMock());

        Sentry_Active_Config__c config = Sentry_Active_Config__c.getOrgDefaults();
        config.IsIssueCreationDisabled__c = false;
        config.IsDebug__c = true;
        config.Sentry_Config__c = 'Test';
        config.Environment_Name__c = 'Test';
        insert config;

        Test.startTest();

        try {
           try{    
                MyException testException = (MyException) Sentry_ExceptionFactory.build(MyException.class);
                testException.setMessage('Something broke.');
                throw testException;
            } catch (Sentry_Exception sentryTestException) {
                Sentry.record(sentryTestException);
                throw sentryTestException;
            }
        } catch (Exception e) {
            ex = e;
        }

        Test.stopTest();

        System.assertNotEquals(null, ex);
    }
    
    @IsTest
    static void RecordwithCustomException() 
    {
        Exception ex;

        Test.setMock(HttpCalloutMock.class, new Sentry_ApiMock());

        Sentry_Active_Config__c config = Sentry_Active_Config__c.getOrgDefaults();
        config.IsIssueCreationDisabled__c = false;
        config.IsDebug__c = true;
        config.Sentry_Config__c = 'Test';
        config.Environment_Name__c = 'Test';
        insert config;

        Test.startTest();
        List<Sentry_LogMessage> lExtraMessages = new List<Sentry_LogMessage>();
     	lExtraMessages.add(new Sentry_LogMessage(Sentry_LogMessage.LEVEL_INFO, Sentry_LogMessage.LEVEL_DEBUG, Sentry_LogMessage.LEVEL_DEBUG,'Testing debug 1', new Map<String, String>()));   
        Sentry.record('Custom Issue Title',new SYS_CustomException('Custom Exception'), lExtraMessages);
        Test.stopTest();

        System.assertEquals(null, ex);
    }
    
    @IsTest
    static void RecordCustomExceptionWithoutSendingToSentry() 
    {
        Exception ex;

        Test.setMock(HttpCalloutMock.class, new Sentry_ApiMock());

        Sentry_Active_Config__c config = Sentry_Active_Config__c.getOrgDefaults();
        config.IsIssueCreationDisabled__c = true;
        config.IsDebug__c = true;
        config.Sentry_Config__c = 'Test';
        config.Environment_Name__c = 'Test';
        insert config;

        Test.startTest();
        List<Sentry_LogMessage> lExtraMessages = new List<Sentry_LogMessage>();
     	lExtraMessages.add(new Sentry_LogMessage(Sentry_LogMessage.LEVEL_INFO, Sentry_LogMessage.LEVEL_DEBUG, Sentry_LogMessage.LEVEL_DEBUG,'Testing debug 1', new Map<String, String>()));   
        Sentry.record('Custom Issue Title',new SYS_CustomException('Custom Exception'), lExtraMessages);
        Test.stopTest();

        System.assertEquals(null, ex);
    }
    
    private class Sentry_ApiMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest param1) {
            HttpResponse response = new HttpResponse();
            response.setStatusCode(200);
            return response;
        }
    }
}