sfdx/force-app/main/default/objects/Account/fields/Stripe_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_ID__c</fullName>
    <description>The Id of the Customer Record in the Stripe data set.</description>
    <externalId>true</externalId>
    <inlineHelpText>The Id of the Customer Record in your Stripe Dashboard.</inlineHelpText>
    <label>Stripe ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Setup_Connection_Data__mdt/Setup_Connection_Data__mdt.object-meta.xml
<CustomObject>
    <label>Setup Connection Data</label>
    <pluralLabel>Setup Connection Data</pluralLabel>
</CustomObject>

sfdx/force-app/main/default/objects/Stripe_Account__c/Stripe_Account__c.object-meta.xml
<CustomObject>
    <description>Custom object representing a connected Stripe Account.</description>
    <label>Stripe Account</label>
    <nameField>
        <label>Stripe Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Stripe_Account__c/fields/Is_Live_Mode__c.field-meta.xml
<CustomField>
    <fullName>Is_Live_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this connection in Live mode?</description>
    <inlineHelpText>Is this connection in Live mode?</inlineHelpText>
    <label>Is Live Mode?</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Account__c/fields/Stripe_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_ID__c</fullName>
    <label>Stripe Account Id</label>
    <description>The ID of the Stripe Account this record represents.</description>
    <inlineHelpText>The ID of the Stripe Account this record represents.</inlineHelpText>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/classes/PostInstallClassTest.cls
/**
 * Created by rpena on 3/12/2024.
 */

@IsTest
public with sharing class PostInstallClassTest {

    @IsTest
    static void testInstallScript() {
        Setup_Connection_Data__mdt testSetupData = test_setupAssistant.getTestStripeConnectionKey();
        test_setupAssistant.setTestGlobalKey(testSetupData);
        test_setupAssistant.insertTestConnectedRecord();
        Test.setMock(HttpCalloutMock.class, new test_setupAssistant.UnifiedConfigMock());

        PostInstallClass postinstall = new PostInstallClass();

        Test.startTest();
        Test.testInstall(postinstall, new Version(1,0), true);
        Test.stopTest();

        List<Stripe_Account__c> stripeAccs = [SELECT Id, Stripe_ID__c, Is_Live_Mode__c FROM Stripe_Account__c];
        System.assertNotEquals(0, stripeAccs.size(), 'No Stripe Account found');
    }


}