sfdx/force-app/main/default/objects/Account/fields/Stripe_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_ID__c</fullName>
    <description>The Id of the Customer Record in the Stripe data set.</description>
    <externalId>true</externalId>
    <inlineHelpText>The Id of the Customer Record in your Stripe Dashboard.</inlineHelpText>
    <label>Stripe ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Setup_Connection_Data__mdt/Setup_Connection_Data__mdt.object-meta.xml
<CustomObject>
    <label>Setup Connection Data</label>
    <pluralLabel>Setup Connection Data</pluralLabel>
</CustomObject>

sfdx/force-app/main/default/objects/Setup_Connection_Data__mdt/fields/Enable_Apex_Debug__c.field-meta.xml
<CustomField>
    <fullName>Enable_Apex_Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Developer config to turn on apex debug logging. This should only ever be false in production.</description>
    <inlineHelpText>Developer config to turn on apex debug logging. This should only ever be false in production.</inlineHelpText>
    <label>Enable Apex Debugging</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Setup_Connection_Data__mdt/fields/Enable_JS_Debug__c.field-meta.xml
<CustomField>
    <fullName>Enable_JS_Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enables the JavaScript debugger output. Should only ever be disabled in production.</description>
    <inlineHelpText>Enables the JavaScript debugger output. Should only ever be disabled in production.</inlineHelpText>
    <label>Enable JavaScript Debugging</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Setup_Connection_Data__mdt/fields/Global_Key__c.field-meta.xml
<CustomField>
    <fullName>Global_Key__c</fullName>
    <description>The key required to register a connection with the Stripe Billing Connector platform.</description>
    <inlineHelpText>The key required to register a connection with the Stripe Billing Connector platform.</inlineHelpText>
    <label>Global Key</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx/force-app/main/default/objects/Setup_Connection_Data__mdt/fields/Middleware_Infrastructure_Version__c.field-meta.xml
<CustomField>
    <fullName>Middleware_Infrastructure_Version__c</fullName>
    <defaultValue>&quot;v1&quot;</defaultValue>
    <description>This is the version of middleware infrastructure to use for making calls to the middleware. Currently defaults to v1 if no value is set.</description>
    <inlineHelpText>This is the version of middleware infrastructure to use for making calls to the middleware. Currently defaults to v1 if no value is set.</inlineHelpText>
    <label>Middleware Infrastructure Version</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>v1</fullName>
                <default>true</default>
                <label>v1</label>
            </value>
            <value>
                <fullName>v2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Account__c/Stripe_Account__c.object-meta.xml
<CustomObject>
    <description>Custom object representing a connected Stripe Account.</description>
    <label>Stripe Account</label>
    <nameField>
        <label>Stripe Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stripe Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Stripe_Account__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>Composite key is a generated, unique key the connector used identify this Stripe Account connection. This is generated by concatenating of the Stripe Account ID and the Stripe Account livemode</description>
    <externalId>true</externalId>
    <inlineHelpText>Composite key is a generated, unique key the connector used identify this Stripe Account connection. This is generated by concatenating of the Stripe Account ID and the Stripe Account livemode</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Account__c/fields/Is_Live_Mode__c.field-meta.xml
<CustomField>
    <fullName>Is_Live_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this connection in Live mode?</description>
    <inlineHelpText>Is this connection in Live mode?</inlineHelpText>
    <label>Is Live Mode?</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Account__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this connection the Primary connection?</description>
    <inlineHelpText>Is this connection the Primary connection?</inlineHelpText>
    <label>Is Primary?</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Account__c/fields/Stripe_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_ID__c</fullName>
    <label>Stripe Account Id</label>
    <description>The ID of the Stripe Account this record represents.</description>
    <inlineHelpText>The ID of the Stripe Account this record represents.</inlineHelpText>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/classes/test_utilities.cls
@IsTest
public with sharing class test_utilities {
    static Test_Tools testTools = new Test_Tools();

    @IsTest
    static void testDmlManager() {
        String profile = Test_Tools.PROFILE_CHATTER_FREE_USER;
        String uniqueId = 'dmlUnprivileged';
        User unprivUser = testTools.insertUser(profile, uniqueId);

        Exception unknownAccessModifier;
        Exception unknownAccessObject;
        Exception unknownAccessField;
        Exception unprivilegedObject;
        Exception unprivilegedField;
        try {
            Map<String, Map<String, Set<String>>> failedAccess = new Map<String, Map<String, Set<String>>> {
                    'Account' => new Map<String, Set<String>> {
                        'Foo' => new Set<String> {'bar'}
                    }
            };
            dmlManager.checkAccess(failedAccess);
        } catch (Exception e) {
            unknownAccessModifier = e;
        }

        try {
            Map<String, Map<String, Set<String>>> failedAccess = new Map<String, Map<String, Set<String>>> {
                    'Foo' => new Map<String, Set<String>> {
                        'Delete' => new Set<String> {}
                    }
            };
            dmlManager.checkAccess(failedAccess);
        } catch (Exception e) {
            unknownAccessObject = e;
        }

        try {
            Map<String, Map<String, Set<String>>> failedAccess = new Map<String, Map<String, Set<String>>> {
                    'Account' => new Map<String, Set<String>> {
                        'Read' => new Set<String> {'bar'}
                    }
            };
            dmlManager.checkAccess(failedAccess);
        } catch (Exception e) {
            unknownAccessField = e;
        }

        try {
            Map<String, Map<String, Set<String>>> failedAccess = new Map<String, Map<String, Set<String>>> {
                    'Account' => new Map<String, Set<String>> {
                        'Delete' => new Set<String> {}
                    }
            };
            System.runAs(unprivUser) {
                dmlManager.checkAccess(failedAccess);
            }
        } catch (Exception e) {
            unprivilegedObject = e;
        }

        try {
            Map<String, Map<String, Set<String>>> failedAccess = new Map<String, Map<String, Set<String>>> {
                    'User' => new Map<String, Set<String>> {
                        'Read' => new Set<String> {'AccountId'}
                    }
            };

            System.runAs(unprivUser) {
                dmlManager.checkAccess(failedAccess);
            }
        } catch (Exception e) {
            unprivilegedField = e;
        }

        Map<String, Map<String, Set<String>>> access = new Map<String, Map<String, Set<String>>> {
                'Account' => new Map<String, Set<String>> {
                        'Create' => new Set<String> {'Name'},
                        'Read' => new Set<String> {'Name'},
                        'Update' => new Set<String> {'Name'},
                        'Delete' => new Set<String> {}
                }
        };

        dmlManager.checkAccess(access);

        System.assertNotEquals(null, unknownAccessModifier, 'Got an exception for unknown access modifier');
        System.assertNotEquals(null, unknownAccessObject, 'Got an exception for unknown access object');
        System.assertNotEquals(null, unknownAccessField, 'Got an exception for unknown access field');
        System.assertNotEquals(null, unprivilegedObject, 'Got an exception for unprivileged object');
        System.assertNotEquals(null, unprivilegedField, 'Got an exception for unprivileged field');
    }

    @IsTest
    static public void getPrimaryStripeAccount() {
        Stripe_Account__c stripeAccount = new Stripe_Account__c();
        String stipeAcctId = 'acct_1234567890';
        stripeAccount.Stripe_ID__c = stipeAcctId;
        stripeAccount.Is_Live_Mode__c = false;
        stripeAccount.External_ID__c = stipeAcctId + '|' + stripeAccount.Is_Live_Mode__c;
        stripeAccount.Name = stipeAcctId;
        stripeAccount.Is_Primary__c = true;
        insert(stripeAccount);

        Test.startTest();
        Stripe_Account__c result = utilities.getPrimaryStripeAccount();
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assertEquals(result.Stripe_ID__c, stipeAcctId);
    }

    @IsTest
    static public void idsToQueryString() {
        Set<Id> ids = new Set<Id> {
            '001000000000000AAA',
            '001000000000000BBB',
            '001000000000000CCC'
        };

        String query = utilities.idsToQueryString(ids);
        System.assertEquals('(\'001000000000000AAA\',\'001000000000000BBB\',\'001000000000000CCC\')', query);
    }
    
    @IsTest
    static public void isUsingV2Middleware() {
        Setup_Connection_Data__mdt testSetupData = test_setupAssistant.getTestStripeConnectionKey();
        testSetupData.Middleware_Infrastructure_Version__c = 'v2';
        test_setupAssistant.setTestGlobalKey(testSetupData);
        test_setupAssistant.insertTestConnectedRecord();
        Test.setMock(HttpCalloutMock.class, new test_setupAssistant.UnifiedConfigMock());

        Test.startTest();
        Boolean isV2 = utilities.isUsingV2Middleware();
        Test.stopTest();

        System.assert(isV2, true);
    }

    @IsTest
    static public void isCPQEnabled() {
        Test.startTest();
        Boolean isCpqEnabled = utilities.isCpqEnabled();
        Test.stopTest();

        System.assert(isCpqEnabled, true);
    }


    @IsTest
    static public void testPackageVersion() {
        Test.startTest();
        String packageVersion = utilities.getPackageVersion();
        Test.stopTest();

        System.assert(packageVersion != null);
    }

    @IsTest
    static public void testPackageVersionString() {
        Test.startTest();
        String packageVersion = utilities.getPackageVersionString();
        Test.stopTest();

        System.assert(packageVersion != null);
    }

    @IsTest
    static void testGetSobjectByMap() {
        Map<String, Object> q = new Map<String, Object> {
            'Account__c' => '123'
        };

        Test.startTest();
        SBQQ__Quote__c quote = (SBQQ__Quote__c) utilities.getSobjectByMap(q, 'Quote__c', 'SBQQ__');
        Test.stopTest();

        System.assertNotEquals(null, quote);
        System.assertEquals('123', quote.SBQQ__Account__c);
    }

    @IsTest
    static void testGetConnectionKey() {
        Exception ex;
        Setup_Connection_Data__mdt testSetupData = test_setupAssistant.getTestStripeConnectionKey();
        test_setupAssistant.setTestGlobalKey(testSetupData);

        String key = utilities.getStripeConnectionKey();

        utilities.setupConfigMetadata.clear();

        try {
            utilities.getStripeConnectionKey();
        } catch (Exception e) {
            ex = e;
        }

        System.assertNotEquals(null, ex, 'Got an exception');
        System.assertEquals(testSetupData.Global_Key__c, key, 'Got the right key');
    }

    @IsTest
    static void testGetOAuthSigningKey() {
        Setup_Connection_Data__mdt testSetupData = test_setupAssistant.getTestStripeConnectionKey();
        test_setupAssistant.setTestGlobalKey(testSetupData);

        Blob key = utilities.getOAuthStateSigningKey();

        utilities.setupConfigMetadata.clear();

        Blob failed = utilities.getOAuthStateSigningKey();

        System.assertEquals(null, failed, 'returns null with no record set');
        System.assertNotEquals(null, key, 'Returns a value with record set');
    }

    @IsTest
    static void testIsDevModeEnabled() {
        Setup_Connection_Data__mdt testSetupData = test_setupAssistant.getTestStripeConnectionKey();
        test_setupAssistant.setTestGlobalKey(testSetupData);

        testSetupData.Enable_JS_Debug__c = true;

        Boolean yep1 = utilities.isDeveloperModeEnabled();
        Boolean yepJs = utilities.isJSDebuggingEnabled();
        Boolean nopeApex2 = utilities.isApexDebuggingEnabled();

        testSetupData.Enable_Apex_Debug__c = true;

        Boolean yepAll = utilities.isDeveloperModeEnabled();
        Boolean yepJs2 = utilities.isJSDebuggingEnabled();
        Boolean yepApex = utilities.isApexDebuggingEnabled();

        utilities.setupConfigMetadata.clear();

        Boolean nopeAll = utilities.isDeveloperModeEnabled();
        Boolean nopeJs = utilities.isJSDebuggingEnabled();
        Boolean nopeApex = utilities.isApexDebuggingEnabled();

        System.assertEquals(false, nopeAll, 'Nope all');
        System.assertEquals(false, nopeJs, 'Nope JS');
        System.assertEquals(false, nopeApex, 'Nope Apex');
        System.assertEquals(true, yep1, 'Yep all');
        System.assertEquals(true, yepJs, 'Yep JS');
        System.assertEquals(false, nopeApex2, 'Nope Apex 2');
        System.assertEquals(true, yepAll, 'Yep all 2');
        System.assertEquals(true, yepJs2, 'Yep JS 2');
        System.assertEquals(true, yepApex, 'Yep Apex');
    }
}