sfdx/force-app/main/default/objects/Stripe_Connection__c/Stripe_Connection__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Stripe_Connection</label>
</CustomObject>

sfdx/force-app/main/default/objects/Stripe_Connection__c/fields/Salesforce_Connected__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Connected__c</fullName>
    <description>Is Salesforce Connected?</description>
    <inlineHelpText>Is Salesforce Connected?</inlineHelpText>
    <defaultValue>false</defaultValue>
    <label>Salesforce Connected</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Connection__c/fields/Stripe_Connected__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Connected__c</fullName>
    <description>Is Stripe Connected?</description>
    <inlineHelpText>Is Stripe Connected?</inlineHelpText>
    <defaultValue>false</defaultValue>
    <label>Stripe Connected</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Sync_Record__c/Sync_Record__c.object-meta.xml
<CustomObject>
    <description>This object tracks sync reports for the Stripe Salesforce Connector.</description>
    <label>Sync Record</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sync Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Sync_Record__c/fields/Primary_Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Object_Type__c</fullName>
    <description>Stores the primary object type</description>
    <inlineHelpText>This field contains the type of the Primary Record related to this Sync Record.</inlineHelpText>
    <label>Primary Object Type</label>
    <type>TextArea</type>
</CustomField>

sfdx/force-app/main/default/objects/Sync_Record__c/fields/Primary_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Primary_Record_ID__c</fullName>
    <description>Stores the Primary Record Id</description>
    <inlineHelpText>The Record Id of the Primary Record for this Sync Record.</inlineHelpText>
    <label>Primary Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Sync_Record__c/fields/Resolution_Message__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Message__c</fullName>
    <label>Sync Message</label>
    <description>The error message produced from the sync request.</description>
    <inlineHelpText>This field contains the message produced from the sync request.</inlineHelpText>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx/force-app/main/default/objects/Sync_Record__c/fields/Resolution_Status__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Status__c</fullName>
    <label>Sync Status</label>
    <description>The status of the sync.</description>
    <inlineHelpText>The sync status which can be one of the following: Success, Error, Skipped, or Resolved.</inlineHelpText>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/objects/Sync_Record__c/fields/Secondary_Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Object_Type__c</fullName>
    <description>Stores the secondary object type</description>
    <inlineHelpText>This field contains the type of the Secondary Record related to this Sync Record.</inlineHelpText>
    <label>Secondary Object Type</label>
    <type>TextArea</type>
</CustomField>

sfdx/force-app/main/default/objects/Sync_Record__c/fields/Secondary_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Record_ID__c</fullName>
    <description>Stores the Secondary Record Id</description>
    <inlineHelpText>The Record Id of the Secondary Record for this Sync Record.</inlineHelpText>
    <label>Secondary Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/classes/relatedSyncRecordsController.cls
public with sharing class relatedSyncRecordsController {
    @AuraEnabled
    public static String getRelatedSyncRecords(Id recordId) {
        responseData rd = new responseData(); 
        Boolean hasSyncRecords = false;
        try {
            Stripe_Connection__c stripeConnectRec = Stripe_Connection__c.getOrgDefaults(); 
            
            if(stripeConnectRec.Id != null && stripeConnectRec.Salesforce_Connected__c && stripeConnectRec.Stripe_Connected__c) {    
                //gets a list sync records to display in component
                List<Sync_Record__c> syncRecordList = [SELECT Id, Name, Primary_Record_ID__c, Primary_Object_Type__c, Secondary_Record_ID__c, Secondary_Object_Type__c, Resolution_Status__c, Resolution_Message__c, CreatedDate
                                                        FROM Sync_Record__c
                                                        WHERE (Primary_Record_ID__c = :recordId
                                                        OR Secondary_Record_ID__c = :recordId)
                                                        WITH SECURITY_ENFORCED
                                                        ORDER BY CreatedDate DESC];   

                if (!syncRecordList.isEmpty()) {
                    hasSyncRecords = true;  
                    rd.put('syncRecordList',syncRecordList); 
                } 
            }
        } catch(QueryException e) {  
            rd.put('missingPermSet',true);  
            return rd.getJsonString();
        } catch (Exception e) {
            rd.addError(e);
        }
        rd.put('hasSyncRecords',hasSyncRecords);
        return rd.getJsonString();
    }
}