sfdx/force-app/main/default/objects/Stripe_Connection__c/Stripe_Connection__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Stripe_Connection</label>
</CustomObject>

sfdx/force-app/main/default/objects/Stripe_Connection__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>The API key to use for communicating with the Stripe Billing Connector platform.</description>
    <inlineHelpText>The API key to use for communicating with the Stripe Billing Connector platform.</inlineHelpText>
    <label>API Key</label>
    <type>TextArea</type>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Connection__c/fields/Salesforce_Connected__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Connected__c</fullName>
    <description>Is Salesforce Connected?</description>
    <inlineHelpText>Is Salesforce Connected?</inlineHelpText>
    <defaultValue>false</defaultValue>
    <label>Salesforce Connected</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Connection__c/fields/Stripe_Connected__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Connected__c</fullName>
    <description>Is Stripe Connected?</description>
    <inlineHelpText>Is Stripe Connected?</inlineHelpText>
    <defaultValue>false</defaultValue>
    <label>Stripe Connected</label>
    <type>Checkbox</type>
</CustomField>

sfdx/force-app/main/default/objects/Stripe_Connection__c/fields/Sync_Record_Retention__c.field-meta.xml
<CustomField>
    <fullName>Sync_Record_Retention__c</fullName>
    <description>How many records to retain when pruning Sync Record Records.</description>
    <inlineHelpText>How many records to retain when pruning Sync Record Records.</inlineHelpText>
    <label>Sync Record Retention</label>
    <type>TextArea</type>
</CustomField>

sfdx/force-app/main/default/objects/Sync_Record__c/Sync_Record__c.object-meta.xml
<CustomObject>
    <description>This object tracks sync reports for the Stripe Salesforce Connector.</description>
    <label>Sync Record</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sync Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Sync_Record__c/fields/Primary_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Primary_Record_ID__c</fullName>
    <description>Stores the Primary Record Id</description>
    <inlineHelpText>The Record Id of the Primary Record for this Sync Record.</inlineHelpText>
    <label>Primary Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Sync_Record__c/fields/Resolution_Status__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Status__c</fullName>
    <label>Sync Status</label>
    <description>The status of the sync.</description>
    <inlineHelpText>The sync status which can be one of the following: Success, Error, Skipped, or Resolved.</inlineHelpText>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/classes/test_syncRecordRetentionTrigger.cls
@isTest
public with sharing class test_syncRecordRetentionTrigger {
    @isTest
    static public void test_syncRecordRetentionTrigger() {
        Stripe_Connection__c stripeConnectRec = new Stripe_Connection__c(); 
        stripeConnectRec.Stripe_Connected__c = true;
        stripeConnectRec.Salesforce_Connected__c = true;
        stripeConnectRec.API_Key__c = 'testPackageGUID';
        stripeConnectRec.Sync_Record_Retention__c = '100';
        upsert stripeConnectRec;

        List<Sync_Record__c> syncRecordsToInsert = new List<Sync_Record__c>();
        for(Integer i = 0; i < 500; i++) {
            Sync_Record__c syncRec = new Sync_Record__c(
                Primary_Record_ID__c = 'Order' + i,
                Resolution_Status__c = 'Resolved'
                );
            syncRecordsToInsert.add(syncRec);
        }
        
        Test.startTest();   
        insert syncRecordsToInsert;
        Test.stopTest();

        List<Sync_Record__c> syncRecordList = [SELECT Id, Resolution_Status__c, CreatedDate
                                                FROM Sync_Record__c
                                                WHERE Resolution_Status__c = 'Resolved'
                                                WITH SECURITY_ENFORCED
                                                ORDER BY CreatedDate];  
        System.assertEquals(syncRecordList.size(), 100);

    }
}