sfdx/force-app/main/default/objects/Stripe_Connection__c/Stripe_Connection__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Stripe_Connection</label>
</CustomObject>

sfdx/force-app/main/default/objects/Stripe_Connection__c/fields/Sync_Record_Retention__c.field-meta.xml
<CustomField>
    <fullName>Sync_Record_Retention__c</fullName>
    <description>How many records to retain when pruning Sync Record Records.</description>
    <inlineHelpText>How many records to retain when pruning Sync Record Records.</inlineHelpText>
    <label>Sync Record Retention</label>
    <type>TextArea</type>
</CustomField>

sfdx/force-app/main/default/objects/Sync_Record__c/Sync_Record__c.object-meta.xml
<CustomObject>
    <description>This object tracks sync reports for the Stripe Salesforce Connector.</description>
    <label>Sync Record</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sync Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Sync_Record__c/fields/Resolution_Status__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Status__c</fullName>
    <label>Sync Status</label>
    <description>The status of the sync.</description>
    <inlineHelpText>The sync status which can be one of the following: Success, Error, Skipped, or Resolved.</inlineHelpText>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/classes/batchDeleteSyncRecords.cls
global with sharing class batchDeleteSyncRecords implements Database.Batchable<SObject> {
    public batchDeleteSyncRecords() {}

    public List<SObject> start(Database.BatchableContext BC) {

        List<Sync_Record__c> allSuccessAndResolvedSyncRecords = [SELECT Id, Resolution_Status__c, CreatedDate
                                                                 FROM Sync_Record__c
                                                                 WHERE (Resolution_Status__c = 'Resolved'
                                                                 OR Resolution_Status__c = 'Success')
                                                                 WITH SECURITY_ENFORCED
                                                                 ORDER BY CreatedDate ASC];

        Stripe_Connection__c stripeConnectRec = Stripe_Connection__c.getOrgDefaults();

        if(stripeConnectRec.Id != null && stripeConnectRec.Sync_Record_Retention__c != null &&
        (allSuccessAndResolvedSyncRecords.size() > integer.valueof(stripeConnectRec.Sync_Record_Retention__c))) {
            return allSuccessAndResolvedSyncRecords;
        }
        return new List<SObject>();
    }

    public void execute(Database.BatchableContext c, List<SObject> scope) {
        try {
            delete scope;
        } catch(Exception e) {
            errorLogger.create('Batch Delete Sync Records', e);
        } 
    }
    public void finish(Database.BatchableContext BC) {}
}