sfdx/force-app/main/default/objects/Order_Stripe_Coupon__c/Order_Stripe_Coupon__c.object-meta.xml
<CustomObject>
    <description>Custom object representing a Stripe Coupon that has been created and synced as part of a Salesforce order.</description>
    <label>Order Stripe Coupon</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Coupon Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Stripe Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Order_Stripe_Coupon__c/fields/Amount_Off__c.field-meta.xml
<CustomField>
    <fullName>Amount_Off__c</fullName>
    <description>The amount that is taken off the subtotal for the duration of the coupon.</description>
    <inlineHelpText>Amount (in the user's currency) that will be taken off the subtotal of any invoices for this customer.</inlineHelpText>
    <label>Amount Off</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Order_Stripe_Coupon__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Indicates how long the coupon is valid for. Values include once, forever, or repeating.</description>
    <inlineHelpText>One of forever, once, and repeating. Describes how long a customer who applies this coupon will get the discount.</inlineHelpText>
    <label>Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>once</fullName>
                <default>true</default>
                <label>once</label>
            </value>
            <value>
                <fullName>repeating</fullName>
            </value>
            <value>
                <fullName>forever</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/objects/Order_Stripe_Coupon__c/fields/Duration_In_Months__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Months__c</fullName>
    <description>If duration is repeating, the number of months the coupon applies. Null if coupon duration is forever or once.</description>
    <inlineHelpText>If duration is repeating, the number of months the coupon applies. Null if coupon duration is forever or once.</inlineHelpText>
    <label>Duration In Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Order_Stripe_Coupon__c/fields/Max_Redemptions__c.field-meta.xml
<CustomField>
    <fullName>Max_Redemptions__c</fullName>
    <description>Maximum number of times a coupon can be redeemed across all customers.</description>
    <inlineHelpText>Maximum number of times this coupon can be redeemed, in total, across all customers, before it is no longer valid.</inlineHelpText>
    <label>Max Redemptions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Order_Stripe_Coupon__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>The name of the coupon.</description>
    <label>Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Order_Stripe_Coupon__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The Id of the Order Record in the Salesforce data set.</description>
    <inlineHelpText>The Id of the Order Record in Salesforce.</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Order_Lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx/force-app/main/default/objects/Order_Stripe_Coupon__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <label>Order Item</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipName>Order_Item_Lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx/force-app/main/default/objects/Order_Stripe_Coupon__c/fields/Percent_Off__c.field-meta.xml
<CustomField>
    <fullName>Percent_Off__c</fullName>
    <description>The percentage off that is taken off the subtotal for the duration of the coupon.</description>
    <inlineHelpText>Percent that will be taken off the subtotal of any invoices for this customer for the duration of the coupon.</inlineHelpText>
    <label>Percent Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Order_Stripe_Coupon__c/fields/Quote_Stripe_Coupon_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stripe_Coupon_Id__c</fullName>
    <description>The unique identifier for the initial coupon this coupon was duplicated from.</description>
    <inlineHelpText>The Id of the Quote Stripe Coupon Record in Salesforce that this coupon was duplicated from.</inlineHelpText>
    <label>Quote Stripe Coupon ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Quote_Line_Stripe_Coupon_Association__c/Quote_Line_Stripe_Coupon_Association__c.object-meta.xml
<CustomObject>
    <description>Custom junction object linking a Stripe Coupon and a CPQ Quote Line.</description>
    <label>Quote Line Stripe Coupon Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Quote Line Stripe Coupon Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Stripe Coupon Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Quote_Line_Stripe_Coupon_Association__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipName>Quote_Line_In_Association</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx/force-app/main/default/objects/Quote_Line_Stripe_Coupon_Association__c/fields/Quote_Stripe_Coupon__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stripe_Coupon__c</fullName>
    <label>Quote Stripe Coupon</label>
    <referenceTo>Quote_Stripe_Coupon__c</referenceTo>
    <relationshipName>Stripe_Coupon_In_Quote_Line_Association</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx/force-app/main/default/objects/Quote_Stripe_Coupon__c/Quote_Stripe_Coupon__c.object-meta.xml
<CustomObject>
    <description>Custom object representing a Stripe Coupon.</description>
    <label>Quote Stripe Coupon</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Coupon Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Stripe Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <validationRules>
        <fullName>Duration_In_Months_Set_For_Repeating</fullName>
        <description>When you use the value repeating for duration, you must specify duration_in_months as the number of months that the coupon repeatedly applies to.</description>
        <active>true</active>
        <errorConditionFormula>AND(ISPICKVAL(Duration__c, "repeating"), ISBLANK(Duration_In_Months__c))</errorConditionFormula>
        <errorMessage>The Duration_In_Months__c param must be set when creating a coupon with a repeating duration.</errorMessage>
    </validationRules>
   <validationRules>
        <fullName>Either_Coupon_Type_Off_Is_Set</fullName>
        <description>Stripe Coupon has either Percent Off or Amount Off set.</description>
        <active>true</active>
        <errorConditionFormula>AND(ISBLANK(Amount_Off__c), ISBLANK(Percent_Off__c))</errorConditionFormula>
        <errorMessage>Must provide Percent_Off__c or Amount_Off__c on a Stripe Coupon.</errorMessage>
    </validationRules>
    <validationRules>
        <fullName>Only_One_Coupon_Type_Off_Is_Set</fullName>
        <description>Stripe Coupon does not have both Percent Off or Amount Off set.</description>
        <active>true</active>
        <errorConditionFormula>AND(NOT(ISBLANK(Amount_Off__c)), NOT(ISBLANK(Percent_Off__c)))</errorConditionFormula>
        <errorMessage>Received both Percent_Off__c and Amount_Off__c parameters. Please pass in only one.</errorMessage>
    </validationRules>
    <validationRules>
        <fullName>Percent_Off_Is_In_Range</fullName>
        <description>Percent_Off__c value should be between 0 and 100.</description>
        <active>true</active>
        <errorConditionFormula>AND(NOT(ISBLANK(Percent_Off__c)), Percent_Off__c > 100.0)</errorConditionFormula>
        <errorMessage>Percent_Off__c value must be greater than 0 and less or equal to 100.</errorMessage>
    </validationRules>
    <validationRules>
        <fullName>Amount_Off_and_Percent_Off_Not_Updated</fullName>
        <description>You cannot change `Amount_Off__c` or `Percent_Off__c` after the coupon is created in Stripe.</description>
        <active>true</active>
        <errorConditionFormula>AND(NOT(ISBLANK(Stripe_ID__c)), OR(ISCHANGED(Amount_Off__c), ISCHANGED(Percent_Off__c)))</errorConditionFormula>
        <errorMessage>You cannot update Amount_Off__c or Percent_Off__c after the coupon has been created.</errorMessage>
    </validationRules>
    <validationRules>
        <fullName>Duration_Not_Updated</fullName>
        <description>You cannot change `Duration__c` after the coupon is created in Stripe.</description>
        <active>true</active>
        <errorConditionFormula>AND(NOT(ISBLANK(Stripe_ID__c)), OR(ISCHANGED(Duration__c)))</errorConditionFormula>
        <errorMessage>You cannot update Duration__c after the coupon has been created.</errorMessage>
    </validationRules>
</CustomObject>

sfdx/force-app/main/default/objects/Quote_Stripe_Coupon__c/fields/Max_Redemptions__c.field-meta.xml
<CustomField>
    <fullName>Max_Redemptions__c</fullName>
    <description>Maximum number of times a coupon can be redeemed across all customers.</description>
    <label>Max Redemptions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx/force-app/main/default/objects/Quote_Stripe_Coupon__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>The name of the Stripe coupon.</description>
    <label>Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx/force-app/main/default/objects/Quote_Stripe_Coupon_Association__c/Quote_Stripe_Coupon_Association__c.object-meta.xml
<CustomObject>
    <description>Custom junction object linking a Stripe Coupon and a CPQ Quote.</description>
    <label>Quote Stripe Coupon Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Quote Stripe Coupon Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Stripe Coupon Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Quote_Stripe_Coupon_Association__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <description>The Id of the Quote Record in the Salesforce data set.</description>
    <inlineHelpText>The Id of the Quote Record in Salesforce.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipName>Quote_In_Association</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx/force-app/main/default/objects/Quote_Stripe_Coupon_Association__c/fields/Quote_Stripe_Coupon__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stripe_Coupon__c</fullName>
    <label>Quote Stripe Coupon</label>
    <referenceTo>Quote_Stripe_Coupon__c</referenceTo>
    <relationshipName>Stripe_Coupon_In_Quote_Association</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx/force-app/main/default/classes/OrderCouponTriggerHandler.cls
public with sharing class OrderCouponTriggerHandler {
    public class CouponException extends Sentry_Exception {}

    private Map<Id, Id> quoteIdsToOrderIds = null;
    private Map<Id, SBQQ__QuoteLine__c> quoteLines = null;
    // the order coupons that are bulk persisted at the end of the trigger execution
    private List<Order_Stripe_Coupon__c> orderCouponsToSave = null;

    private static final String FIELD_CURRENCY_ISO_CODE = constants.FIELD_CURRENCY_ISO_CODE;

    public OrderCouponTriggerHandler(Map<Id, Id> quoteIdsToOrderIds) {
        this.refreshState(quoteIdsToOrderIds);
    }

    public void refreshState(Map<Id, Id> quoteIdsToOrderIds) {
        if (quoteIdsToOrderIds == null) {
            this.quoteIdsToOrderIds = new Map<Id, Id>();
        } else {
            this.quoteIdsToOrderIds = quoteIdsToOrderIds;
        }

        orderCouponsToSave = new List<Order_Stripe_Coupon__c>();
        quoteLines = new Map<Id, SBQQ__QuoteLine__c>();
    }

    public void process() {
        removePreviouslyProcessedOrders();
        processQuoteCoupons();
        processQuoteLineCoupons();
    }

    // in case the user has workflows that would cause the trigger to fire twice, let's ensure we don't create duplicate Order Stripe Coupons
    public void removePreviouslyProcessedOrders() {
        // create the reverse map of order id -> quote id
        Map<Id, Id> orderIdsToQuoteIds = new Map<Id, Id>();
        for (Id quoteId : quoteIdsToOrderIds.keySet()) {
            orderIdsToQuoteIds.put(quoteIdsToOrderIds.get(quoteId), quoteId);
        }

        Map<Id, OrderItem> orderItemsById = new Map<Id, OrderItem>([SELECT Id, OrderId FROM OrderItem WHERE OrderId = :quoteIdsToOrderIds.values()]);

        // query for all Order Stripe Coupons that are tied to these orders or order items
        List<Order_Stripe_Coupon__c> coupons = [
            SELECT
                Order__c,
                Order_Item__c
            FROM Order_Stripe_Coupon__c
            WHERE
                Order__c = :quoteIdsToOrderIds.values()
                OR Order_Item__c = :orderItemsById.keySet()
        ];

        for (Order_Stripe_Coupon__c coupon : coupons) {
            Id orderId = null;
            if (coupon.Order_Item__c != null) {
                orderId = orderItemsById.get(coupon.Order_Item__c).OrderId;
            } else if (coupon.Order__c != null) {
                orderId = coupon.Order__c;
            }

            // this should really never happen since an Order Stripe Coupon 
            // should always be created with either Order__c or Order_Item__c fields set
            if (orderId == null) {
                continue;
            }

            // remove any quote we have already processed
            Id quoteId = orderIdsToQuoteIds.get(orderId);
            if (quoteIdsToOrderIds.containsKey(quoteId)) {
                quoteIdsToOrderIds.remove(quoteId);
            }
        }
    }

    public void processQuoteCoupons() {
        // SECTION: fetch the quote->order coupon data
        List<Quote_Stripe_Coupon_Association__c> qscAssociations = getQuoteCouponAssociations(quoteIdsToOrderIds.keySet());

        if (qscAssociations.isEmpty()) {
            return;
        }

        for (Quote_Stripe_Coupon_Association__c assoc : qscAssociations) {
            Quote_Stripe_Coupon__c quoteCoupon = assoc.Quote_Stripe_Coupon__r;

            // if the coupon is null, log an error and move on, as other orders may be fine.
            if (quoteCoupon == null || quoteCoupon.Id == null) {
                CouponException ex = (CouponException) Sentry_ExceptionFactory.build(CouponException.class);
                ex.setMessage('No Quote_Stripe_Coupon__c found for Quote_Stripe_Coupon_Association__c');
                ex.context.put('MapOfQuoteIdsToOrderIds', quoteIdsToOrderIds);
                ex.context.put('Quote_Stripe_Coupon_Association__c.Id', assoc.Id);
                ex.context.put('SBQQ__Quote__c.Id', assoc.Quote__c);
                ex.context.put('Order.Id', quoteIdsToOrderIds.get(assoc.Quote__c));
                errorLogger.create('OrderCouponTriggerHandler-CouponNotFound', ex);
                continue;
            }

            // clone the quote coupon
            Id orderId = quoteIdsToOrderIds.get(assoc.Quote__c);
            Order_Stripe_Coupon__c orderCoupon = createOrderCoupon(quoteCoupon);
            orderCoupon.Order__c = orderId;

            orderCouponsToSave.add(orderCoupon);
        }
    }

    public void processQuoteLineCoupons() {
        // SECTION: fetch the quote line -> order line coupon data
        quoteLines = getQuoteLinesByIds(quoteIdsToOrderIds.keySet());

        if (quoteLines.isEmpty()) {
            return;
        }

        Set<Id> quoteLineIds = quoteLines.keySet();
        List<Quote_Line_Stripe_Coupon_Association__c> qlscAssociations = getQuoteLineCouponAssociations(quoteLineIds);
        
        if (qlscAssociations.isEmpty()) {
            return;
        }

        Map<Id, Id> orderItemByQuoteLineId = getOrderItemIdByQuoteLineIds(quoteLineIds);

        for (Quote_Line_Stripe_Coupon_Association__c assoc : qlscAssociations) {
            Quote_Stripe_Coupon__c quoteCoupon = assoc.Quote_Stripe_Coupon__r;

            // if the coupon is null, log an error and move on, as other order lines may be fine.
            if (quoteCoupon == null || quoteCoupon.Id == null) {
                CouponException ex = (CouponException) Sentry_ExceptionFactory.build(CouponException.class);
                ex.setMessage('No Quote_Stripe_Coupon__c found for Quote_Line_Stripe_Coupon_Association__c');
                ex.context.put('MapOfQuoteIdsToOrderIds', quoteIdsToOrderIds);
                ex.context.put('Quote_Line_Stripe_Coupon_Association__c.Id', assoc.Id);
                ex.context.put('SBQQ__QuoteLine__c', assoc.Quote_Line__c);
                SBQQ__QuoteLine__c ql = quoteLines.get(assoc.Quote_Line__c);
                ex.context.put('SBQQ__Quote__c', (ql != null) ? ql.SBQQ__Quote__c : null);
                ex.context.put('Order.Id', (ql != null) ? quoteIdsToOrderIds.get(ql.Id) : null);
                errorLogger.create('OrderCouponTriggerHandler-CouponNotFound', ex);
                continue;
            }

            // clone the quote coupon
            Order_Stripe_Coupon__c orderCoupon = createOrderCoupon(quoteCoupon);
            orderCoupon.Order_Item__c = orderItemByQuoteLineId.get(assoc.Quote_Line__c);

            orderCouponsToSave.add(orderCoupon);
        }
    }

    public void persistChanges() {
        // SECTION: save the order and order item coupons
        Database.insert(orderCouponsToSave);
    }

    public static Order_Stripe_Coupon__c createOrderCoupon(Quote_Stripe_Coupon__c quoteCoupon) {
        // clone the Quote Coupon on the quote, it will have a different Id
        Order_Stripe_Coupon__c osc = new Order_Stripe_Coupon__c(
            Amount_Off__c = quoteCoupon.Amount_Off__c,
            Duration__c = quoteCoupon.Duration__c,
            Duration_In_Months__c = quoteCoupon.Duration_In_Months__c,
            Max_Redemptions__c = quoteCoupon.Max_Redemptions__c,
            Name__c = quoteCoupon.Name__c,
            Percent_Off__c = quoteCoupon.Percent_Off__c,
            Quote_Stripe_Coupon_Id__c = quoteCoupon.Id
        );

        if (UserInfo.isMultiCurrencyOrganization()) {
            osc.put(FIELD_CURRENCY_ISO_CODE, quoteCoupon.get(FIELD_CURRENCY_ISO_CODE));
        }

        return osc;
    }

    private List<Quote_Stripe_Coupon_Association__c> getQuoteCouponAssociations(Set<Id> quoteIds) {
        List<String> fields = new List<String> {
            'Quote__c',
            'Quote_Stripe_Coupon__c',
            'Quote_Stripe_Coupon__r.Id',
            'Quote_Stripe_Coupon__r.Amount_Off__c',
            'Quote_Stripe_Coupon__r.Duration__c',
            'Quote_Stripe_Coupon__r.Duration_In_Months__c',
            'Quote_Stripe_Coupon__r.Max_Redemptions__c',
            'Quote_Stripe_Coupon__r.Name__c',
            'Quote_Stripe_Coupon__r.Percent_Off__c'
        };

        List<String> multiCurrFields = new List<String> {
            'Quote_Stripe_Coupon__r.' + FIELD_CURRENCY_ISO_CODE,
            FIELD_CURRENCY_ISO_CODE
        };

        return utilities.execMultiCurrLookupQuery(
                Quote_Stripe_Coupon_Association__c.SObjectType,
                'Quote__c',
                quoteIds,
                fields,
                multiCurrFields
        );
    }

    private Map<Id, SBQQ__QuoteLine__c> getQuoteLinesByIds(Set<Id> quoteIds) {
        return new Map<Id, SBQQ__QuoteLine__c>([
            SELECT
                Id,
                SBQQ__Quote__c,
                (
                    SELECT
                        Id,
                        SBQQ__QuoteLine__c,
                        OrderId
                    FROM SBQQ__OrderProducts__r
                )
            FROM SBQQ__QuoteLine__c
            WHERE SBQQ__Quote__c = :quoteIds
        ]);
    }

    private List<Quote_Line_Stripe_Coupon_Association__c> getQuoteLineCouponAssociations(Set<Id> quoteLineIds) {
        List<String> fields = new List<String> {
            'Id',
            'Quote_Line__c',
            'Quote_Line__r.Id',
            'Quote_Line__r.SBQQ__Quote__c',
            'Quote_Stripe_Coupon__c',
            'Quote_Stripe_Coupon__r.Id',
            'Quote_Stripe_Coupon__r.Amount_Off__c',
            'Quote_Stripe_Coupon__r.Duration__c',
            'Quote_Stripe_Coupon__r.Duration_In_Months__c',
            'Quote_Stripe_Coupon__r.Max_Redemptions__c',
            'Quote_Stripe_Coupon__r.Name__c',
            'Quote_Stripe_Coupon__r.Percent_Off__c'
        };

        List<String> multiCurrFields = new List<String> {
            'Quote_Stripe_Coupon__r.' + FIELD_CURRENCY_ISO_CODE,
            FIELD_CURRENCY_ISO_CODE
        };

        return utilities.execMultiCurrLookupQuery(
                Quote_Line_Stripe_Coupon_Association__c.SObjectType,
                'Quote_Line__c',
                quoteLineIds,
                fields,
                multiCurrFields
        );
    }

     private Map<Id, Id> getOrderItemIdByQuoteLineIds(Set<Id> quoteLineIds) {
        List<OrderItem> orderItems = [
            SELECT Id, SBQQ__QuoteLine__c
            FROM OrderItem
            WHERE SBQQ__QuoteLine__c IN :quoteLineIds
        ];

         Map<Id, Id> orderItemsByQuoteLineId = new Map<Id, Id>();
         for (OrderItem orderItem: orderItems)
         {
            orderItemsByQuoteLineId.put(orderItem.SBQQ__QuoteLine__c, orderItem.Id);
         }
         return orderItemsByQuoteLineId;
    }      
}